### ISSUE TITLE
All usernames are 'TAKEN'

### ISSUE THREAD

**Issue by gxzass** [luczavestoski/Username-Checker#2]
All the usernames are taken, even the ones that should be available. I've had the same thing when I wrote my own code and did this. Can you try to find a workaround, I'm also trying to find an other way. 
![image](https://user-images.githubusercontent.com/83720143/117222019-c69cc180-ae0a-11eb-9573-b8014a64712e.png)

_Cheers_

**Comment by luczavestoski** [comment]
Unfortunately this tool has to be rewritten to continue to work. 

“As of 10/17/2020, the R6Tab API will remain private due to API abuse. No applications past the closing will be accepted. I apoligize for any inconvienace this may have caused.”
https://github.com/Tabwire/R6Tab-API

Automation through selenium may be possible, or finding a new API. If you do find any new possibilities feel free to make a pull request or open a new issue.
